name: Docker
run-name: "Docker · edramkai/${{ inputs.image }}:${{ inputs.tag }}"

on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: 请选择需要构建的镜像
        options:
          - laravel
          - greatmall
        required: true
      tag:
        type: string
        description: 请输入镜像的版本号
        default: latest

permissions:
  contents: read

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    with:
      context: ${{ inputs.tag == 'latest' && format('./{0}', inputs.image) || format('./{0}/{1}', inputs.image, inputs.tag) }}
      output: image
      platforms: linux/amd64,linux/arm64
      push: true
      sign: "false"
      meta-images: edramkai/${{ inputs.image }}
      meta-tags: type=raw,value=${{ inputs.tag }}
      meta-flavor: latest=false
    secrets:
      registry-auths: |
        - registry: docker.io
          username: edramkai
          password: ${{ secrets.DOCKERHUB_TOKEN }}
